### PR TITLE
make it build post gcc 4.6 and add the spec file from yaml

### PR DESCRIPTION
**Pull request by alinelena**

### CODE REVIEW

**Comment by karip** [comment]
I took the changes for the missing unistd.h includes.

But, I don't really want to have generated files (.spec) in the source repository, so I didn't take those changes. The translations are not part of the build by default because I haven't had time to add them, but the generated translation files are needed to make the build pass.

**Comment by alinelena** [comment]
Hi, 

I need the spec file generated if I want to build it automatically in the obs...
it does nothing with te yaml file. In more modern times yaml was totally
deprecated and packages provide only the .spec.

Regards,
Alin

On Sun, Jul 26, 2015 at 03:35:04am -0700, karip wrote:
> I took the changes for the missing unistd.h includes.
> 
> But, I don't really want to have generated files (.spec) in the source repository, so I didn't take those changes. The translations are not part of the build by default because I haven't had time to add them, but the generated translation files are needed to make the build pass.
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/karip/harbour-file-browser/pull/18#issuecomment-124967625

-- 
Without Questions there are no Answers!
________________________________________________________________________________
Dr. Alin Marin ELENA
http://alin.elena.space/
________________________________________________________________________________

**Comment by karip** [comment]
Ok, I've added the spec file to the repository.

I also added automatic .qm file generation (it does it in the .pro file), so the yaml and spec files should be ok as they are.

**Comment by alinelena** [comment]
Hi karip,

still no i18n installed.. you can check here.

https://build.merproject.org/package/live_build_log/home:alin:extra/harbour-file-browser/sailfishos_1.1.7.25/armv8el

Alin

On Sun, Jul 26, 2015 at 04:06:10am -0700, karip wrote:
> Ok, I've added the spec file to the repository.
> 
> I also added automatic .qm file generation (it does it in the .pro file), so the yaml and spec files should be ok as they are.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/karip/harbour-file-browser/pull/18#issuecomment-124972320

-- 
Without Questions there are no Answers!
________________________________________________________________________________
Dr. Alin Marin ELENA
http://alin.elena.space/
________________________________________________________________________________

**Comment by karip** [comment]
Can you be more specific what should be merged? I have already included some parts of this pull request in the master.

Actually, it would be more helpful if a new pull request was made with the required fixes. I can then close this one.

**Comment by Maldela** [comment]
I had this segfault on startup too. It was caused by the access function in globals.cpp. I fixed it and made a pull request.

**Pull request closed without merging**
