### PR TITLE
Create file-browser_sv.qm

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

### CODE REVIEW

**Comment by eson57** [comment]
I also have a cleaned up file-browser.ts, for other translators to use, if you want it.

**Comment by karip** [comment]
Thanks for the translation!

The translation file should have .ts extension, not .qm extension, so I renamed it.

What do you mean by "I also have a cleaned up file-browser.ts, for other translators to use, if you want it."?

**Comment by eson57** [comment]
Oh... sorry for the faulty file extension. I must have copied name from the qm file I used for testing.
Before I started translating, I cleaned up your "file-browser_de.ts", meaning I deleted all german translations and replaced the <translation> tags with <translation type="unfinished">. That way I could use Qt-Linguist the way it is supposed to, for translation.
If you want the file, you can download from my domain, or I can make a new pull request.
https://svenskasprakfiler.se/tempfiles/file-browser.ts

**Comment by karip** [comment]
Perhaps file-browser.ts is not needed, it would be extra overhead to keep it up-to-date if new texts are added to the app. Also, people can create a new empty translation file with lupdate, like this:

    lupdate src -ts src/i18n/file-browser_XX.ts

**Comment by eson57** [comment]
Ok... I wasn't aware about the lupdate command.

**Pull request merged**
