### PR TITLE
Folder as a command line argument

### PR DESCRIPTION
**Pull request by direc85**
I quickly whipped together a way to give an absolute path as a command line argument. This fixes Issue #9

While this works for me, I have a feeling that some sanity checks should be done...

### CODE REVIEW

**Comment by karip** [comment]
Thanks for the pull request!

I tested this by calling `harbour-file-browser /home/nemo/Downloads` from Terminal. Here’s what I found:

* If the File Browser has already been launched from the app grid, calling harbour-file-browser will open another instance of the app. Having two File Browsers running at the same time is confusing to the user.
* If the app hasn’t been launched from the app grid, then there is only one instance running. But, the user can then launch File Browser again from the app grid and ends up having two instances running. Confusing.
* Calling the app directly as `harbour-file-browser` will create it as a child process for the calling app. If the calling app is closed, then File Browser gets also closed. This is bad if the user has started a long file copy process and the app just dies.

There are few other reasons why calling File Browser from other apps is problematic:

* The user may not have the app installed.
* The user may have an older version of File Browser which doesn’t support command line arguments.

Do you have any opinions about the issues above?

**Comment by direc85** [comment]
Hi

Thanks for feedback! Here are my comments:
- It looks like many other applications can be launched twice using launcher icon and behave in the same way, given extra parameters or not. The application should handle situations so that the already opened one would grab the parameters and handle them accordingly, but I don't know how this could be achieved.
- As a power user I don't find that confusing, but for average user it sure is. How could we force single instance?
- The calling application must fork the process so that it is an independent process instead. I know only basics about that. Perhaps there is some sort of invoker we could use?
- The correct way would be for the calling application to somehow check if `harbour-file-browser` is installed and of new enough version. I am not aware of any simple way to check this (and it would have to pass Harbour checks, too). I think it is possible to use QFile to check if a file exists?
- If an application can check that a file exists, it could check its date, too, and deduce the result from there. And if such is the case, example code is required for anyone to implement it.

One thought crossed my mind; it seems `/tmp` is world writable. What if the calling application wrote, say, `/tmp/harbour-file-browser.path` file with a path or filename in it, and File Browser would monitor that filename and react accordingly? Of course, `/home/nemo` could be used, too.

What methods there are for Sailfish OS processes to communicate with each other (other than `/tmp`)?

Could we utilise `xdg-open` for this?

**Comment by direc85** [comment]
Whoops, sorry. I clicked "Close and comment" by mistake.

**Comment by karip** [comment]
Calling `xdg-open` to open folders in file browsers is a good idea. It allows users to decide which file browser they want to use: the Sailfish native file browser, File Browser, File Tug, CargoDock etc. You don't want to force users to use File Browser.

Currently, it opens the path in the web browser, which is not very useful. But, there are ways to configure `xdg-open` to open different apps.

`xdg-open` seems to run the app in a separate process. I don't know if it solves the double instance problem. Also, I don't know how it passes the path to the app. If I open a PDF file `xdg-open my.pdf` then the PDF viewer isn't opened twice. I think this requires a bit more research.

The downside of `xdg-open` is that files cannot be opened in file browsers. For instance, calling `xdg-open` with a path to a jpeg image opens it in the image viewer, not in the file browser. So, only folders would open in file browsers when using `xdg-open`. Do you think that is a problem?

Actually, your pull request code doesn't work for paths which point to files. It opens the file as a folder. Is that a problem?

**Comment by direc85** [comment]
I think the correct approach would be to use `xdg-open` to open directories in File Browser. Perhaps a second argument could be used to select a file in that folder, so that the file would automatically get selected in File Browser? That way only the folder association would need to be done.

If not, we are back in the original request, and that is completely fine by me.

I can implements checks for the argument. Is it a file, is it a folder, does it even exist, can the location be accessed at all etc. but what still remains is the double instance problem. I had a look at `/usr/share/applications/sailfish-office*.desktop` files and there are strong clues about how it could be achieved. I will look into it next week.

**Comment by direc85** [comment]
Well, that was fast...

It turns out that the source code for `sailfish-office` is available here in GitHub, and the answer, I think, lies in [this file](https://github.com/sailfishos/sailfish-office/blob/fdf5a30468f0b79ac975f2215abf3e51b435e3df/dbusadaptor.cpp). I will look at it later and try to replicate the functionality.

**Comment by karip** [comment]
Another open issue is how users can configure `xdg-open` to open paths in File Browser. As I said, currently `xdg-open` opens them in the web browser. Does Jolla allow apps to change the mappings?

As you can see, there is quite a lot of things to consider to make this work nicely. That's why I hadn't implemented this myself. :)

**Comment by Arusekk** [comment]
It should be enough to add a line specifying the MIME type (`inode/directory`) inside the `.desktop` file, as done here:

https://github.com/sailfishos/sailfish-office/blob/fdf5a30468f0b79ac975f2215abf3e51b435e3df/sailfish-office-openfile.desktop#L10

And of course adding `%F` (being the file path) or `%U` (being an URI) to the end of `Exec=` line.
As far as I know, Jolla store allows specifying the mime type, like it is done in all the text editors available.

**Comment by sebix** [comment]
> As you can see, there is quite a lot of things to consider to make this work nicely. That's why I hadn't implemented this myself. :)

Sorry for joining late in this discussion. I was also looking for the same functionality as @direc85 and @llelectronics. I understand your remarks, @karip but I am unsure if they are blocking the new functionality by worsening the user experience or introducing bugs. As far as I see, the functionality can be improved though, but not easily and not entirely inside your great app. For example if an (advanced!) user opens a second instance of the app, this a) affects only advanced users and b) does not cause harm or trigger bugs. Maybe this PR could be merged and released despite the provided additional features are not perfect?

**Comment by karip** [comment]
You can find a more advanced version of File Browser which accepts folders as command line parameters at https://github.com/ichthyosaurus/harbour-file-browser

**Comment by sebix** [comment]
Which one is in the Jolla Store? (The app which is in the store links this repository here)

**Comment by karip** [comment]
Jolla store has this version (1.8.0). OpenRepos has the new version.

**Comment by direc85** [comment]
Thank you for the feedback, and to @karip for pointing out the fork.

I don't have time to develop this feature any further, and it turned out to be way more complex to do properly than I initially thought. Also, the feature exists in the fork already. I'm closing this PR, but if anyone want's to complete this, feel free to do so!

**Comment by sebix** [comment]
As https://github.com/ichthyosaurus/harbour-file-browser does not have Issues activated, I'm asking here: Is it planned that @ichthyosaurus takes over the App in the Jolla Store?

**Comment by ichthyosaurus** [comment]
First, I wasn't aware of that, so thanks for pointing it out! I activated issues now.

@karip and I already talked about this but I failed to follow up due to real life and then came a pandemic (sorry! @karip). Currently, I don't have the necessary free time to develop and/or properly maintain any of my apps. Plus Jolla's SDK is broken in my setup and I didn't have time to debug it yet.

There were a few issues to be resolved before my fork would be clear to become "official" but I _think_ (I'm not entirely sure) I fixed them already.

I can also take maintainership of the Jolla Store app entry (but I can almost promise there won't be any changes before at least January). @karip Just tell if that's still what you would like to do with your pet project. If so, please tell me what info you need...

**Comment by karip** [comment]
@ichthyosaurus: You can become the maintainer of the Jolla Store app. You have to create a [Jolla Harbour](https://harbour.jolla.com/) account and give the name of your user id to me. I can then ask Jolla to transfer the app to you.

**Comment by ichthyosaurus** [comment]
(done)

**Pull request closed without merging**
